on: [pull_request]

name: Tests
concurrency:
  group: check-tests-main-${{github.event.pull_request.number}}
  cancel-in-progress: true
jobs:
  test:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Check Tests
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: npm install
      - run: npm test
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: 1
      - uses: testomatio/check-tests@stable
        with:
          framework: mocha
          tests: 'tests/**_test.js'
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-on-empty: true
          has-tests-label: true
          github-pat: ${{ secrets.GH_PAT }}
          enable-documentation: true
          documentation-branch: 'master'
